.PHONY: clean All

All:
	@echo "----------Building project:[ CPPrnp - Debug ]----------"
	@cd "CPPrnp" && "$(MAKE)" -f  "CPPrnp.mk"
clean:
	@echo "----------Cleaning project:[ CPPrnp - Debug ]----------"
	@cd "CPPrnp" && "$(MAKE)" -f  "CPPrnp.mk" clean
