.PHONY: clean All

All:
	@echo "----------Building project:[ CCP - Debug ]----------"
	@cd "CCP" && "$(MAKE)" -f  "CCP.mk"
clean:
	@echo "----------Cleaning project:[ CCP - Debug ]----------"
	@cd "CCP" && "$(MAKE)" -f  "CCP.mk" clean
